Fix flaky MQTT Java test
Every ~30 runs, test case `sessionRedelivery` was failing with error:
```
[ERROR] sessionRedelivery{TestInfo}  Time elapsed: 1.298 s  <<< ERROR!
org.eclipse.paho.client.mqttv3.MqttException: Client is currently disconnecting
	at com.rabbitmq.mqtt.test.MqttTest.sessionRedelivery(MqttTest.java:535)
```

The problem was that the Java client was still in connection state
`DISCONNECTING` which throws a Java exception when `connect()`ing.

So, the problem was client side.

We already check for `isConnected()` to be `false` which internally
checks for
```
conState == CONNECTED
```
However, there is no public client API to check for other connection
states. Therefore just waiting for a few milliseconds fixes the flake.