Bump node versions for selenium tests
Search for `Error: Cannot find module 'node:events'` in internet
suggests using at least node 16.6.

(cherry picked from commit 6517c7fe6c0aa2139c3f6ae52a3b506f46bd94c7)