package-generic-unix: set FULL=1 (#16897)
Without this change, re-running `make package-generic-unix` could
produce strange complilation errors like:
```
== Compilation error in file lib/rabbitmq/cli/formatters/pretty_table.ex ==
** (MatchError) no match of right hand side value:

    false

    lib/rabbitmq/cli/formatters/pretty_table.ex:17: (module)
warning: you must pass return_diagnostics: true when invoking Kernel.ParallelCompiler functions
  (elixir 1.19.5) lib/kernel/parallel_compiler.ex:324: Kernel.ParallelCompiler.spawn_workers/3
  (stdlib 7.3) erl_eval.erl:920: :erl_eval.do_apply/7
  (stdlib 7.3) erl_eval.erl:484: :erl_eval.expr/6
  (mix 1.19.5) lib/mix/project.ex:557: Mix.Project.in_project/4
  (elixir 1.19.5) lib/file.ex:2013: File.cd!/2
  (stdlib 7.3) erl_eval.erl:920: :erl_eval.do_apply/7
```

By disabling erlang.mk's dependency optimisation, we avoid such strange
issues.

(cherry picked from commit ecfe2a5903bbaa3d3f2adac371ef3d8d8b3061fa)