Add bazel-test make target so that we can run tests in bazel quickly
How do we solve this one @pjk25?

    $ make bazel-test DEP=deps/rabbit SUITE=queue_type
    /usr/local/bin/bazel test //deps/rabbit:queue_type_SUITE --config=ci
    ERROR: Config value 'ci' is not defined in any .rc file
    make: *** [mk/bazel.mk:16: bazel-test] Error 2

Signed-off-by: Gerhard Lazu <gerhard@lazu.co.uk>