Add debug utilities to Docker image
We need these to debug various rabbitmq-related issues. Ephemeral debug
containers are not enabled on GKE Autopilot (not sure if GKE enables
this alpha feature at all), so we are doing this instead.

    error: ephemeral containers are disabled for this cluster (error from server: "the server could not find the requested resource").

Backport to v3.9.x & v3.8.x if build passes

Pair @Gsantomaggio

Signed-off-by: Gerhard Lazu <gerhard@lazu.co.uk>