CI: Use 'bazel cquery' to find OCI tests
Bazel 7 can't seem to resolve Osiris 1.7.1 when running this query using
'bazel query':

    ERROR: Error computing the main repository mapping: in module dependency chain <root> -> rabbitmq_osiris@1.7.1: module not found in registries: rabbitmq_osiris@1.7.1

Switching to cquery resolves the tests correctly. It also prints the
configuration hashes per case which we need to cut off with awk.

(cherry picked from commit a12ea5fdd9d2b9b677f1ab3db460ad30b8b788de)