Fix export using python 3
Without `.encode()` you get this error:

```
TypeError: a bytes-like object is required, not str
```

Also use `with` when appropriate